Repository TesseractCoding/NeoAlgo-Docs, pull requests merged in 2021-05, with the labels that each got.

#292 CI/CD: Add a GitHub Action Bot to tag PRs with merge conflicts
  .github/workflows/conflicts.yml
Labels: Level3, PR:Peer-Review, gssoc21

#325 Product of count of bits of each element in array is added
  docs/mathematics/product-of-count-of-bits-of-each-elements.mdx
  sidebars.js
Labels: merge-conflicts

#217 Inorder traversal added
  docs/data-structures/inorder_traversal.mdx
  sidebars.js
Labels: PR:Under-Review, do-not-merge-yet, gssoc21, merge-conflicts

#407 Tower of hanoi added
  docs/data-structures/tower-of-hanoi.mdx
  sidebars.js
Labels: PR:Under-Review, gssoc21, merge-conflicts

#305 Added Doc for Number is Power of 2
  docs/mathematics/number-power-of-2.mdx
  sidebars.js
Labels: Level3, PR:Peer-Review, gssoc21

#431 Added Documentation for Depth of tree
  docs/data-structures/depth-of-tree.mdx
  sidebars.js
Labels: Level3, PR:Peer-Review, gssoc21

#461 Added Documentation for Diameter of Binary Tree
  docs/competitive-programming/diameter-of-BT.mdx
  sidebars.js
Labels: Level3, PR:Ready-to-Merge, gssoc21

#175 Prim algo
  docs/graph-algorithms/prims-algorithm.mdx
  sidebars.js
Labels: Level3, PR:Under-Review, gssoc21, merge-conflicts

#318 count no. of bits in a number added
  docs/mathematics/count-bits.mdx
  sidebars.js
Labels: PR:Under-Review, merge-conflicts

#479 article on generate subsequences added
  docs/competitive-programming/generate-subsequences.mdx
  sidebars.js
Labels: Level3, gssoc21

#420 Next prime number
  docs/mathematics/next-prime-number.mdx
  sidebars.js
Labels: merge-conflicts

#457 snake traversal added
  docs/mathematics/snake-traversal-of-matrix.mdx
  sidebars.js
Labels: PR:Under-Review, gssoc21

#219 Postorder traversal added
  docs/data-structures/postorder_traversal.mdx
  sidebars.js
Labels: Level3, gssoc21

#226 Two pointer documentation
  docs/searching-algorithms/two-pointer.mdx
  sidebars.js
Labels: Level3, PR:Under-Review, do-not-merge-yet, gssoc21

#498 Added Documentation for Double Ended Queue
  docs/data-structures/double-ended-queue.mdx
  sidebars.js
Labels: Level3, PR:Peer-Review, PR:Under-Review, gssoc21

#468 Added coin change problem
  docs/dynamic-programming/coin-change-problem.mdx
  sidebars.js
Labels: Level3, PR:Under-Review, gssoc21

#382 Minimum in Binary Search Tree(BST) Documentation
  docs/data-structures/minimum-in-bst.mdx
  sidebars.js
Labels: Level3, PR:Peer-Review, PR:Under-Review, gssoc21

#310 Occurrence of a number in array added
  docs/mathematics/occurrence-of-no.-in-array.mdx
  sidebars.js
Labels: PR:Under-Review, gssoc21, merge-conflicts

#487 Phone keypad problem
  docs/competitive-programming/phone-keypad.mdx
  sidebars.js
Labels: gssoc21

#496 ceil in BST added
  docs/data-structures/ceil_in_bst.mdx
  sidebars.js
Labels: gssoc21

#493 Height of binary search tree added
  docs/data-structures/height_BST.mdx
  sidebars.js
Labels: PR:Under-Review, gssoc21, merge-conflicts

#456 Article on ackermann function
  docs/mathematics/ackermann-function.mdx
  sidebars.js
Labels: Level3, PR:Under-Review, gssoc21

#504 Added Documentation for Identical Binary Tree
  docs/competitive-programming/identical-BT.mdx
  sidebars.js
Labels: gssoc21, merge-conflicts

#450 Toggle k-th Bit
  docs/bit-manipulation/toggle-kth-bit.mdx
  sidebars.js
Labels: Level3, PR:Peer-Review, gssoc21

#467 BFS Article after Changes have done
  docs/graph-algorithms/breadth-first-search.md
  docs/graph-algorithms/breadth-first-search.mdx
Labels: PR:Peer-Review, PR:Under-Review, do-not-merge-yet, gssoc21

#326 Sieve of erastothenes || documentation || mathematics
  docs/mathematics/sieve-of-eratosthenes.mdx
  sidebars.js
Labels: PR:Under-Review, gssoc21, merge-conflicts

#300 Painting fence || DP ||documentation
  docs/dynamic-programming/painting-fence.mdx
  sidebars.js
Labels: Level3, PR:Under-Review, gssoc21, merge-conflicts

#499 java code added for counting sort
  docs/sorting-algorithms/counting-sort.mdx
  sidebars.js
Labels: Level2, gssoc21

#519 perfect cube added
  docs/mathematics/perfect-cube.mdx
  sidebars.js
Labels: gssoc21

#516 Article on wine selling problem
  docs/competitive-programming/wine-selling.mdx
  sidebars.js
Labels: gssoc21

#524 Added C code in linear search
  docs/searching-algorithms/linear-search.mdx
Labels: gssoc21

#509 added java code for heap sort
  docs/sorting-algorithms/heap-sort.mdx
Labels: gssoc21, level1

#511 java code for quick sort
  docs/sorting-algorithms/quick-sort.mdx
Labels: PR:Under-Review, gssoc21

#523 Radix sort java code
  docs/sorting-algorithms/radix-sort.mdx
Labels: PR:Under-Review, gssoc21

#510 insertion sort java code
  docs/sorting-algorithms/insertion-sort.mdx
Labels: PR:Under-Review, gssoc21

#534 added Java code for cocktail sort
  docs/sorting-algorithms/cocktail-sort.mdx
Labels: Level2, gssoc21

#535 added javascript code for the stooge sort
  docs/sorting-algorithms/stooge-sort.mdx
Labels: gssoc21

#536 added cpp code for shell sort
  docs/sorting-algorithms/shell-sort.mdx
Labels: PR:Under-Review, gssoc21

#515 Article on print all permutations
  docs/competitive-programming/all-permutations.mdx
  sidebars.js
Labels: gssoc21

#522 Binary Search Documentation
  docs/searching-algorithms/binary-search.mdx
  sidebars.js
Labels: gssoc21

#495 Documentation for Smallest Prime Factor of any number
  docs/mathematics/smallest-prime-factor-of-any-number.mdx
  sidebars.js
Labels: gssoc21

#230 Added Next permutation Docs
  docs/mathematics/next-permutation.mdx
  sidebars.js
Labels: Level3, PR:Under-Review, do-not-merge-yet, gssoc21

#278 Article for the next greatest element for each element in array
  docs/competitive-programming/next-greatest-to-right.mdx
  sidebars.js
Labels: Level3, PR:Under-Review, gssoc21

#279 Article for Infix to postfix conversion
  docs/data-structures/infix-to-postfix.mdx
  sidebars.js
Labels: Level3, PR:Under-Review, gssoc21, merge-conflicts

#280 Moore's voting Algorithm Docs
  docs/miscellaneous/moore-voting-algorithm.mdx
  sidebars.js
Labels: Level3, PR:Peer-Review, gssoc21, merge-conflicts

#195 Unbounded knapsack doc
  docs/dynamic-programming/unbounded-knapsack.mdx
  sidebars.js
Labels: Level3, PR:Under-Review, gssoc21

#417 Invert Binary Tree || Data Structures
  docs/data-structures/invert-binary-tree.mdx
  sidebars.js
Labels: Level3, PR:Under-Review, gssoc21

#433 First occurence of 1 in a sorted array of 0s and 1s Docs
  docs/competitive-programming/first-occurence-1.mdx
  sidebars.js
Labels: Level3, PR:Under-Review, gssoc21

#440 Added Kosaraju's Algorithm
  docs/graph-algorithms/kosarajus-algorithm.mdx
Labels: Level3, PR:Under-Review, do-not-merge-yet, gssoc21

#441 Added documentation on Circle sort
  docs/sorting-algorithms/circle-sort.mdx
  sidebars.js
Labels: Level3, PR:Under-Review, gssoc21

#443 Added documentation on Cutting a Rod problem
  docs/dynamic-programming/cutting-a-rod.mdx
  sidebars.js
Labels: Level3, PR:Under-Review, gssoc21, merge-conflicts

#459 Decimal to Binary Conversion
  docs/mathematics/decimal-to-binary.mdx
  sidebars.js
Labels: PR:Under-Review, do-not-merge-yet, gssoc21

#520 Added Documentation for Middle Element of a Linked List
  docs/data-structures/middle-element-of-LL.mdx
  sidebars.js
Labels: PR:Under-Review, gssoc21

#21 Added the doc guideline
  doc-guideline.md
  docs/doc-guideline.md
Labels: Level3, PR:Under-Review, gssoc21

#242 bubble sort content added
  docs/sorting-algorithms/bubble-sort.md
Labels: Level3, PR:Peer-Review, gssoc21

#539 Article on median of two arrays
  docs/dynamic-programming/median-of-two-arrays.mdx
  sidebars.js
Labels: PR:Peer-Review, PR:Under-Review, gssoc21
