Repository TesseractCoding/NeoAlgo-Docs, pull requests merged in 2021-04, with the labels that each got.

#55 Added Doc for Caesar Cipher
  docs/cryptography/caesar-cipher.md
  docs/cryptography/caesar-cipher.mdx
Labels: GSSoC21, Level3, PR:Peer-Review

#47 Added the article for Interpolation Search
  docs/searching-algorithms/interpolation-search.mdx
  sidebars.js
Labels: GSSoC21, Level3, PR:Under-Review

#45 Add a GH Action to test the Application Build
  .github/workflows/main.yml
Labels: GSSoC21, Level3

#52 Added the article for Armstrong Number
  docs/mathematics/armstrong-number.md
  docs/mathematics/armstrong-number.mdx
  docusaurus.config.js
Labels: GSSoC21, Level3, PR:Peer-Review

#86 Added documentation for factorial of a number
  docs/mathematics/factorial-of-number.mdx
  docs/mathematics/mathematics.md
  sidebars.js
Labels: GSSoC21, Level3, PR:Peer-Review

#70 Made text become dark on hovering for readability
  src/pages/index.js
  src/pages/styles.module.css
Labels: GSSoC21, level2

#87 Added contributing guidelines
  CONTRIBUTING.md
Labels: GSSoC21, Level3, PR:Under-Review

#95 Added Doc for happy Number
  docs/mathematics/happy-number.mdx
  sidebars.js
Labels: GSSoC21, Level3, PR:Peer-Review

#118 Krishnamurthy Number Docs
  docs/mathematics/krishnamurthy-number.mdx
  sidebars.js
Labels: GSSoC21, Level3, PR:Under-Review

#129 Added documentation for Vigenere Cipher
  docs/cryptography/vigenere-cipher.mdx
  sidebars.js
Labels: GSSoC21, Level3, PR:Under-Review

#91 Added Documentation for Data Structures
  docs/data-structures/data-structures.md
  docs/data-structures/data-structures.mdx
Labels: GSSoC21, Level3, PR:Peer-Review

#131 Added Template for NeoAlgoDoc
  ARTICLE-TEMPLATE.mdx
Labels: GSSoC21, PR:Under-Review, level2

#116 Prime Number
  docs/mathematics/prime-number.mdx
  sidebars.js
Labels: GSSoC21, Level3, PR:Peer-Review, urgent

#121 Added Magic Number doc
  docs/mathematics/magic-number.mdx
  sidebars.js
Labels: GSSoC21, Level3, PR:Peer-Review

#124 Added the article for Binary Tree
  docs/data-structures/binary-tree.md
  docs/data-structures/binary-tree.mdx
Labels: GSSoC21, Level3, PR:Peer-Review

#130 Added Neon Number doc
  docs/mathematics/neon-number.mdx
  sidebars.js
Labels: GSSoC21, Level3, PR:Peer-Review

#80 heap sort article added
  docs/sorting-algorithms/heap-sort.mdx
  sidebars.js
Labels: GSSoC21, Level3, PR:Peer-Review

#149 Added doc for Anagram Number
  docs/mathematics/anagram-number.mdx
  sidebars.js
Labels: GSSoC21, Level3, PR:Peer-Review

#79 selection sort article added
  docs/sorting-algorithms/selection-sort.mdx
  sidebars.js
Labels: GSSoC21, Level3, PR:Peer-Review

#148 Added Extended Euclidean Algorithm doc
  docs/mathematics/extended-euclidean-Algorithm.mdx
  sidebars.js
Labels: GSSoC21, Level3, PR:Peer-Review

#141 Added Keyword Cipher doc
  docs/cryptography/keyword-cipher.mdx
  sidebars.js
Labels: GSSoC21, Level3, PR:Peer-Review

#159 Updated Contributing.md
  CONTRIBUTING.md
Labels: GSSoC21, Level0

#144 Pallindrome number
  docs/mathematics/palindrome-number.mdx
  sidebars.js
Labels: Level3, PR:Peer-Review, gssoc21

#78 Added doc for Insertion sort algorithm
  docs/sorting-algorithms/insertion-sort.mdx
  sidebars.js
Labels: Level3, PR:Peer-Review, gssoc21

#162 Sum of Digits Docs
  docs/mathematics/sum-of-digits.mdx
  sidebars.js
Labels: Level3, PR:Peer-Review, gssoc21

#77 Added documentation for linear search
  docs/searching-algorithms/linear-search.md
  docs/searching-algorithms/linear-search.mdx
Labels: Level3, PR:Under-Review, gssoc21

#181 Doc for mystery number
  docs/mathematics/mystery-number.mdx
  sidebars.js
Labels: Level3, PR:Peer-Review, gssoc21

#152 Searching Algorithms
  docs/searching-algorithms/searching-algorithms.md
  docs/searching-algorithms/searching-algorithms.mdx
Labels: Level3, PR:Peer-Review, gssoc21

#143 Added article for Kruskals Algorithm
  docs/graph-algorithms/kruskals-algorithm.mdx
  sidebars.js
Labels: Level3, PR:Peer-Review, gssoc21

#85 Added doc for palindromic linked list
  docs/data-structures/palindromic-linked-list.mdx
  sidebars.js
Labels: Level3, PR:Peer-Review, gssoc21

#147 Documentation for merge sort algorithm
  docs/sorting-algorithms/merge-sort.mdx
  sidebars.js
Labels: Level3, PR:Peer-Review, gssoc21

#184 Added playfair cipher and updated sidebar
  docs/cryptography/playfair-cipher.mdx
  sidebars.js
Labels: PR:Under-Review, gssoc21

#187 Added Railfence cipher
  docs/cryptography/railfence-cipher.mdx
  sidebars.js
Labels: Level3, gssoc21

#176 sum of divisors added
  docs/mathematics/sum-of-divisors.mdx
  sidebars.js
Labels: Level3, PR:Under-Review, gssoc21

#89 Added doc for maximum number formed from the given numbers in an array
  docs/competitive-programming/max-number-from-array.mdx
  sidebars.js
Labels: Level3, gssoc21

#174 count of divisors added
  docs/mathematics/count-of-divisors.mdx
  sidebars.js
Labels: Level3, PR:Under-Review, gssoc21

#168 Count of Digits
  docs/mathematics/count-of-digits.mdx
  sidebars.js
Labels: Level3, gssoc21

#189 Added Documentation for Binary Search Tree
  docs/data-structures/binary-search-tree.mdx
  sidebars.js
Labels: Level3, gssoc21

#170 Reverse a Number
  docs/mathematics/reverse-a-number.mdx
  sidebars.js
Labels: Level3, PR:Under-Review, gssoc21

#186 Article added for Singly Linked list
  docs/data-structures/Singly-Linked-list.mdx
  sidebars.js
Labels: Level3, PR:Peer-Review, gssoc21

#202 Added Homophonic cipher doc
  docs/cryptography/homophonic-cipher.mdx
  sidebars.js
Labels: Level3, gssoc21

#145 Article added for N-Queens Problem
  docs/backtracking/n-queens.md
  docs/backtracking/n-queens.mdx
Labels: Level3, PR:Under-Review, gssoc21

#215 doc for exponential search
  docs/searching-algorithms/exponential-search.mdx
  sidebars.js
Labels: PR:Peer-Review, gssoc21

#200 Added Article for Jump Search
  docs/searching-algorithms/jump-search.mdx
  sidebars.js
Labels: Level3, PR:Peer-Review, gssoc21

#228 Added doc for Vernam Cipher
  docs/cryptography/vernam-cipher.mdx
  sidebars.js
Labels: Level3, gssoc21

#229 Added doc for Catalan number
  docs/mathematics/catalan-number.mdx
  sidebars.js
Labels: Level3, PR:Peer-Review, gssoc21

#123 Quick-sort added
  docs/sorting-algorithms/quick-sort.mdx
  sidebars.js
Labels: Level3, PR:Peer-Review, gssoc21

#282 Article added for Circular Linked list
  docs/data-structures/Circular-Linked-list.mdx
  sidebars.js
Labels: Level3, PR:Peer-Review, gssoc21

#338 Added documentation for Lucky numbers
  docs/mathematics/lucky-numbers.mdx
  sidebars.js
Labels: Level3, PR:Under-Review, gssoc21

#238 Added Documentation for Queue
  docs/data-structures/queue.mdx
  sidebars.js
Labels: Level3, gssoc21

#193 Added documentation for stack
  docs/data-structures/stack-data-structure.mdx
  sidebars.js
Labels: Level3, PR:Under-Review, gssoc21

#387 Added documentation for Affine Cipher
  docs/cryptography/affine-cipher.mdx
  sidebars.js
Labels: Level3, PR:Peer-Review, gssoc21

#134 Counting sort added
  docs/sorting-algorithms/counting-sort.mdx
  sidebars.js
Labels: Level3, gssoc21

#164 adding matrix addition
  docs/mathematics/matrix-addition.mdx
  sidebars.js
Labels: Level3, PR:Peer-Review, gssoc21

#172 adding matrix transpose
  docs/mathematics/matrix-transpose.mdx
  sidebars.js
Labels: Level3, PR:Under-Review, gssoc21

#335 Perfect number Docs
  docs/mathematics/perfect-number.mdx
  sidebars.js
Labels: Level3, gssoc21

#197 adding matrix multiplication
  docs/mathematics/matrix-multiplication.mdx
  sidebars.js
Labels: Level3, PR:Under-Review, gssoc21

#386 Article on factorial of large numbers
  docs/competitive-programming/factorial-of-large-number.mdx
  sidebars.js
Labels: Level3, gssoc21

#317 Euler totient function
  docs/mathematics/euler-totient-function.mdx
  sidebars.js
Labels: Level3, gssoc21

#362 Pascal Triangle
  docs/mathematics/pascal-triangle.mdx
  sidebars.js
Labels: Level3, PR:Peer-Review, gssoc21

#312 binary exponentiation added
  docs/mathematics/binary-exponentiation.mdx
  sidebars.js
Labels: Level3, PR:Peer-Review, gssoc21

#427 Added documentation for Wiggle Sort
  docs/sorting-algorithms/wiggle-sort.mdx
  sidebars.js
Labels: Level3, PR:Peer-Review, gssoc21

#397 Tetrahedral number
  docs/mathematics/tetrahedral-number.mdx
  sidebars.js
Labels: Level3, gssoc21

#394 Hexagonal Number
  docs/mathematics/hexagonal-number.mdx
  sidebars.js
Labels: Level3, gssoc21
